name: plunderphonics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - bcrypt
  - dateutils
  - psycopg2
  - fastapi
  - requests
  - pytest
  - pip
  - sqlalchemy
  - jupyter
  - jedi=0.17.2
  - uvicorn
  - pip
