name: plunderphonics
channels:
  - defaults
  - conda-forge
  - coecms
dependencies:
  - python=3.8
  - bcrypt
  - cryptography
  - dateutils
  - psycopg2
  - fastapi
  - requests
  - pytest
  - pip
  - sqlalchemy
  - jupyter
  - jedi=0.17.2
  - uvicorn
  - python-jose
  - python-multipart
  - passlib
  - dataset
  - pip
  - redis-py=3.5.3
